### ISSUE TITLE
Accurate in an A/S environment?

### ISSUE THREAD

**Issue by Scott972** [awslabs/cost-optimization-ec2-right-sizing#18]
Instances in an A/S environment are  ephemeral, will this account for that or will the results always be the current usage?

**Comment by beomseoklee** [comment]
Hi @Scott972, and sorry for being late. I don't quite understand your question, so can you explain it a little bit more?

**Comment by Scott972** [comment]
@beomseoklee Sure, so docs state that the last two weeks of data are used to determine a 'right size', but in my auto scaling environment instances are being launched and terminated frequently, none of them will hardly live for 2 weeks, so will the data I get take this into account or just the current usage of the current instances in the autoscaling group?

**Comment by beomseoklee** [comment]
@Scott972 Thanks for the detail.

The solution is going to check CloudWatch metrics for the running instances, then recommend the right sizing of running instances. In your case, if you are using auto scaling, many of instances can possibly only have few CloudWatch metrics, but the solution is going to calculate the right sizing based on the metrics within 2 weeks; some instances can only have 5-10 minutes metrics.

I believe auto scaling group instances would have mostly equal usage, so you can refer to the longest running instance among the auto scaling group, and when you get the result, I would recommend you to test as well before putting into your production.
