### ISSUE TITLE
How does this compare to Trusted Advisor reports?

### ISSUE THREAD

**Issue by sidewinder12s** [awslabs/cost-optimization-ec2-right-sizing#2]
I was left wondering after reading through the brief, how does this compare to built in Trusted Advisor reports on cost optimization?

**Comment by milbrya** [comment]
Thanks for your feedback. We have updated the FAQ to include this:
Q: How does this solution differ from the AWS Trusted Advisor Cost Optimization check?

Both the EC2 Right Sizing solution and AWS Trusted Advisor analyze utilization on EC2 instances running any time during the last two weeks. The EC2 Right Sizing solution analyzes all instances with a max CPU utilization lower than 50% and determines a more cost-effective instance type for that workload, if available. In comparison, AWS Trusted Advisor can alert you to low utilization thresholds such as daily CPU utilization of 10% or less and network I/O of 5 MB or less on 4 or more days during the two-week period.

Each tool provides valuable information about your Amazon EC2 usage that can help you lower your costs.

**Comment by manginkr** [comment]
what is the amount of time it takes to run the complete script, please post the steps to implement in manually without cloud formation template
