### ISSUE TITLE
Getting empty S3 bucket after running the solution

### ISSUE THREAD

**Issue by venkatamamidi** [awslabs/cost-optimization-ec2-right-sizing#9]
There appears to be some 'bug' recently introduced where currently, the right sizing solution runs 'fine' but creates empty s3 bucket (with no recommendation csv file). Raised a support case with aws and they said they were able to repro but can't help as it's not 'officially supported'. 

Are more people running into this and/or can some one help fix this? 

FYI - I was able to run it successfully last on March 26th.

**Comment by stevemorad** [comment]
Sorry for the inconvenience. The published solution should be fixed now, and updated GitHub files have been updated too.
